export WORKON_HOME=$HOME/.virtualenvs
VIRTUALENVWRAPPER_PYTHON=$HOME/venv/bin/python
source $HOME/venv/bin/virtualenvwrapper.sh
echo "Welcome to Erick's zsh"
PATH=/sw/bin:/sw/sbin:$PATH:/$HOME/venv/bin
export BASEDIR=Users/edransch/mozilla/build-master

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

EDITOR="vim"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="bira"

alias connect='sudo wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf'
alias lease='sudo dhcpcd'

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias halt='sudo halt'
alias reboot='sudo reboot'
alias exeunt='sudo halt'
alias svim='sudo vim'
alias svi='sudo vim'

alias :q='exit'
alias ls='ls --color=auto'
alias lla='ls -la'
alias lsa='ls -a'

alias vi='vim'
alias qfind='find|grep $1' # quick find

alias grep='grep --color' # always colour grep output

### pacman ###
alias pacman='yaourt'
alias pac='pacman'
alias pacs='pacman -S'
alias pacss='pacman -Ss'
alias pacq='pacman -Q|grep'

alias skype='su skypeuser -c "dbus-launch --exit-with-session skype"'

alias mntcs='sshfs ekgdrans@student.cs.uwaterloo.ca: /mnt/uw'

alias vol='amixer set Master'

### application renaming ###
alias html2pdf='wkhtmltopdf'

### programming ###
alias vgrind='valgrind --leak-check=yes --show-reachable=yes'

function mkcd() { mkdir "$1" && cd "$1"; }

# start, stop, restart, reload - simple daemon management
## usage: start <daemon-name>
## from cinderwick.ca/files/configs/bashrc
start() {
        for arg in $*; do
                sudo /etc/rc.d/$arg start
        done
}
stop() {
        for arg in $*; do
                sudo /etc/rc.d/$arg stop
        done
}
restart() {
        for arg in $*; do
                sudo /etc/rc.d/$arg restart
        done
}
reload() {
        for arg in $*; do
                sudo /etc/rc.d/$arg reload
        done
}


# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git mercurial archlinux github python)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
#

DIRSTACKSIZE=20
setopt autopushd pushdminus pushdsilent pushdtohome

setopt NOCLOBBER


